enum ProtoDmScriptOutputType {
    // Script output should be ignored
    DM_SCRIPT_OUTPUT_TYPE_NONE = 0;
    // Script output should be treated as string
    DM_SCRIPT_OUTPUT_TYPE_STRING = 1;
    // Script output should be treated as doctype code
    DM_SCRIPT_OUTPUT_TYPE_DOCTYPE = 2;
}

message ProtoDmScript {
  // extends DocumentElement
  ProtoDocumentElement parent = 1;

  string content = 2;
  repeated string comChannelUUIDs = 3;
  string uuid = 4;
  bool bindContent = 5;
  ProtoGenerationType generationType = 6;
  ProtoDmScriptOutputType outputType = 7;
}
