# Directories
PROTO_SRC := src
BUILD_DIR := build
TS_OUT := $(BUILD_DIR)/ts
GO_OUT := docframepb
CSHARP_OUT := build

# Phony targets
.PHONY: all clean buf-gen

# Default target
all: buf-gen

# -------------------------------
# Buf generate for all languages
# -------------------------------
buf-gen:
	buf generate --template buf.gen.yaml --path $(PROTO_SRC)

# -------------------------------
# TypeScript output (ts-proto)
# -------------------------------
$(TS_OUT): buf-gen
	mkdir -p $(TS_OUT)
	@echo "TypeScript code generated in $(TS_OUT)"

# -------------------------------
# Go output (generated by buf-gen)
# -------------------------------
$(GO_OUT): buf-gen
	@echo "Go code generated in $(GO_OUT)"

# -------------------------------
# C# output (generated by buf-gen)
# -------------------------------
$(CSHARP_OUT): buf-gen
	@echo "C# code generated in $(CSHARP_OUT)"

# -------------------------------
# Clean generated files
# -------------------------------
clean:
	rm -rf $(BUILD_DIR) $(GO_OUT)/docframe.pb.go $(CSHARP_OUT)/*
