// Code generated by go generate; DO NOT EDIT.
// This file was generated by docframe document element generator
package docframepb


func (ProtoListLevelSetting *ProtoListLevelSetting) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_ListLevelSetting{
			ListLevelSetting: ProtoListLevelSetting,
		},
		Children: nodeChildren,
	}

	return node
}

func (ProtoImageListLevelSetting *ProtoImageListLevelSetting) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_ImageListLevelSetting{
			ImageListLevelSetting: ProtoImageListLevelSetting,
		},
		Children: nodeChildren,
	}

	return node
}

func (ProtoTextListLevelSetting *ProtoTextListLevelSetting) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_TextListLevelSetting{
			TextListLevelSetting: ProtoTextListLevelSetting,
		},
		Children: nodeChildren,
	}

	return node
}

func (ProtoNumberListLevelSetting *ProtoNumberListLevelSetting) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_NumberListLevelSetting{
			NumberListLevelSetting: ProtoNumberListLevelSetting,
		},
		Children: nodeChildren,
	}

	return node
}

func (ProtoUnnumberedListLevelSetting *ProtoUnnumberedListLevelSetting) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_UnnumberedListLevelSetting{
			UnnumberedListLevelSetting: ProtoUnnumberedListLevelSetting,
		},
		Children: nodeChildren,
	}

	return node
}

