// Code generated by go generate; DO NOT EDIT.
// This file was generated by docframe document element generator
package docframepb


func (InputFieldText *ProtoInputFieldText) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_InputFieldText{
			InputFieldText: InputFieldText,
		},
		Children: nodeChildren,
	}

	return node
}

func (InputFieldDate *ProtoInputFieldDate) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_InputFieldDate{
			InputFieldDate: InputFieldDate,
		},
		Children: nodeChildren,
	}

	return node
}

func (InputFieldCheckbox *ProtoInputFieldCheckbox) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_InputFieldCheckbox{
			InputFieldCheckbox: InputFieldCheckbox,
		},
		Children: nodeChildren,
	}

	return node
}

func (InputFieldLabel *ProtoInputFieldLabel) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_InputFieldLabel{
			InputFieldLabel: InputFieldLabel,
		},
		Children: nodeChildren,
	}

	return node
}

func (InputFieldDropdown *ProtoInputFieldDropdown) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_InputFieldDropdown{
			InputFieldDropdown: InputFieldDropdown,
		},
		Children: nodeChildren,
	}

	return node
}

