// Code generated by go generate; DO NOT EDIT.
// This file was generated by docframe document element generator
package docframepb


func (setColor *ProtoSetColor) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_SetColor{
			SetColor: setColor,
		},
		Children: nodeChildren,
	}

	return node
}

func (unsetColor *ProtoUnsetColor) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_UnsetColor{
			UnsetColor: unsetColor,
		},
		Children: nodeChildren,
	}

	return node
}

func (coloredArea *ProtoColoredArea) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_ColoredArea{
			ColoredArea: coloredArea,
		},
		Children: nodeChildren,
	}

	return node
}

