// Code generated by go generate; DO NOT EDIT.
// This file was generated by docframe document element generator
package docframepb


func (ProtoCropSettings *ProtoCropSettings) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_CropSettings{
			CropSettings: ProtoCropSettings,
		},
		Children: nodeChildren,
	}

	return node
}

func (ProtoFlipSettings *ProtoFlipSettings) ToNode(children ...Message) *Node {
	nodeChildren := make([]*Node, len(children))
	for i, c := range children {
		nodeChildren[i] = c.ToNode()
	}

	node := &Node{
		Object: &Node_FlipSettings{
			FlipSettings: ProtoFlipSettings,
		},
		Children: nodeChildren,
	}

	return node
}

